<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title ?? 'Report' }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 14px; color: #222; }
        h1 { text-align: center; }
        .meta { margin-bottom: 30px; }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }
        th, td {
            border: 1px solid #666;
            padding: 8px 10px;
            text-align: left;
        }
        th {
            background: #f2f2f2;
        }
        .footer { text-align: right; font-size: 12px; color: #888; margin-top: 40px; }
    </style>
</head>
<body>
    <h1>{{ $title ?? 'Report' }}</h1>
    <div class="meta">
        <strong>Date:</strong> {{ $date ?? \Carbon\Carbon::now()->format('Y-m-d') }}
    </div>

    {{-- Example: Data Summary Table --}}
    @isset($tableHeadings)
    <table>
        <thead>
            <tr>
                @foreach ($tableHeadings as $heading)
                    <th>{{ $heading }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach ($row as $cell)
                        <td>{{ $cell }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($tableHeadings) }}">No data available.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    @endisset

    {{-- Example: Place for charts/images --}}
    @isset($chartPath)
        <div>
            <img src="{{ $chartPath }}" alt="Chart" style="max-width:100%;height:auto;">
        </div>
    @endisset

    {{-- Example: Additional Notes --}}
    @isset($notes)
        <div>
            <strong>Notes:</strong>
            <p>{{ $notes }}</p>
        </div>
    @endisset

    <div class="footer">
        Generated by Municipality of Kotor – {{ \Carbon\Carbon::now()->format('Y-m-d H:i') }}
    </div>
</body>
</html>