name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    name: Run Laravel Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: my_mysql
          MYSQL_USER: OpKotor
          MYSQL_PASSWORD: bidonkaktus123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, intl, pdo, pdo_mysql
          ini-values: |
            post_max_size=256M
            upload_max_filesize=256M
          tools: composer

      - name: Install Composer Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Set up storage and permissions
        run: |
          mkdir storage\framework\cache
          mkdir storage\framework\sessions
          mkdir storage\framework\views
          mkdir bootstrap\cache
          icacls storage /grant Everyone:(OI)(CI)F /T
          icacls bootstrap\cache /grant Everyone:(OI)(CI)F /T

      - name: Copy environment file and configure DB
        shell: pwsh
        run: |
          Copy-Item .env.example .env -Force
          (Get-Content .env) -replace '^DB_CONNECTION=.*', 'DB_CONNECTION=mysql' |
            ForEach-Object { $_ -replace '^DB_HOST=.*', 'DB_HOST=127.0.0.1' } |
            ForEach-Object { $_ -replace '^DB_PORT=.*', 'DB_PORT=3306' } |
            ForEach-Object { $_ -replace '^DB_DATABASE=.*', 'DB_DATABASE=my_mysql' } |
            ForEach-Object { $_ -replace '^DB_USERNAME=.*', 'DB_USERNAME=OpKotor' } |
            ForEach-Object { $_ -replace '^DB_PASSWORD=.*', 'DB_PASSWORD=bidonkaktus123' } |
            Set-Content .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run Migrations
        run: php artisan migrate --force --no-interaction

      - name: Run Tests
        run: php artisan test