name: Laravel CI/CD

on:
  push:
    branches:
      - main # Workflow se pokreće kada se izvrši push u granu "main".
  pull_request:
    branches:
      - main # Workflow se pokreće kada se otvori pull request koji cilja granu "main".

jobs:
  laravel-tests:
    name: Run Laravel Tests # Naziv posla koji se izvršava unutar workflow-a.
    runs-on: ubuntu-latest # Workflow se izvršava na najnovijoj verziji Ubuntu operativnog sistema.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        # Ovaj korak preuzima kod iz repozitorijuma kako bi bio dostupan za dalju obradu.

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4' # Postavlja se verzija PHP-a koja će se koristiti (u ovom slučaju 8.4).
          extensions: mbstring, bcmath, intl, pdo, pdo_mysql
          # Instaliraju se potrebne PHP ekstenzije koje aplikacija zahtijeva.
          ini-values: |
            post_max_size=256M
            upload_max_filesize=256M
          # Podešavaju se PHP ini vrijednosti kao što su maksimalna veličina fajlova za upload.
          coverage: none # Pokrivenost koda nije uključena.
          tools: composer # Instalira se Composer kao dodatni alat.

      - name: Install Composer Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
        # Instaliraju se zavisnosti definisane u `composer.json` fajlu.

      - name: Copy environment file
        run: |
          if [ -f .env.example ]; then
            cp .env.example .env;
          else
            echo "No .env.example file found. Skipping.";
          fi
        # Ako postoji `.env.example` fajl, kopira se kao `.env`. Ako ne postoji, preskače se korak.

      - name: Generate app key
        run: php artisan key:generate
        # Generiše se sigurnosni ključ aplikacije i dodaje u `.env` fajl.

      - name: Run Migrations
        run: php artisan migrate --force --no-interaction
        # Pokreću se migracije kako bi se kreirala ili ažurirala baza podataka.

      - name: Run Tests
        run: php artisan test
        # Pokreću se testovi aplikacije definisani u Laravel projektu.