name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    name: Run Laravel Tests
    runs-on: ubuntu-latest

    steps:
    # Preuzimanje koda iz repozitorijuma
    - name: Checkout Code
      uses: actions/checkout@v3

    # Postavljanje PHP okruženja
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, bcmath, intl, pdo, pdo_mysql
        ini-values: |
          post_max_size=256M
          upload_max_filesize=256M
        coverage: none
        tools: composer

    # Instalacija Composer zavisnosti
    - name: Install Composer Dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    # Kopiranje environment fajla
    - name: Copy environment file
      run: |
        if [ -f .env.example ]; then
          cp .env.example .env
        else
          echo "No .env.example file found. Skipping."
        fi

    # Generisanje Laravel ključa
    - name: Generate app key
      run: php artisan key:generate

    # Pokretanje migracija
    - name: Run Migrations
      run: php artisan migrate --force --no-interaction

    # Pokretanje testova
    - name: Run Tests
      run: php artisan test