name: Tests

# Ovaj workflow se pokreće na različite događaje:
on:
  push:
    branches:
      - master # Pokreće se kada se promjene push-uju u granu master.
      - '*.x'  # Pokreće se kada se push-uju promjene u bilo koju granu koja završava sa ".x".
  pull_request: # Pokreće se za svaki pull request.
  schedule:
    - cron: '0 0 * * *' # Pokreće se svaki dan u ponoć.

permissions:
  contents: read # Workflow ima samo dozvolu za čitanje sadržaja repozitorijuma.

jobs:
  tests:
    runs-on: ubuntu-latest # Pokreće se na Ubuntu najnovijem operativnom sistemu.

    strategy:
      fail-fast: true # Ako jedan od poslova ne uspije, ostali se odmah prekidaju.
      matrix:
        php: [8.2, 8.3, 8.4] # Testira se na više verzija PHP-a.

    name: PHP ${{ matrix.php }} # Dinamičko ime posla koji uključuje verziju PHP-a.

    steps:
      # Korak 1: Preuzimanje koda iz repozitorijuma.
      - name: Checkout code
        uses: actions/checkout@v4

      # Korak 2: Postavljanje PHP okruženja.
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} # Koristi verziju PHP-a iz matrice.
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite # Instalira potrebne PHP ekstenzije.
          coverage: none # Onemogućava pokrivenost koda.

      # Korak 3: Instalacija Composer zavisnosti.
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
        # Instalira zavisnosti definisane u composer.json fajlu.

      # Korak 4: Kopiranje environment fajla.
      - name: Copy environment file
        run: cp .env.example .env
        # Kopira .env.example u .env fajl.

      # Korak 5: Generisanje aplikacionog ključa.
      - name: Generate app key
        run: php artisan key:generate
        # Generiše aplikacioni ključ za Laravel aplikaciju.

      # Korak 6: Pokretanje testova.
      - name: Execute tests
        run: php artisan test
        # Pokreće testove aplikacije koristeći Artisan komandu.