name: Update Changelog

# Ovaj workflow se pokreće kada se objavi nova verzija (release).
on:
  release:
    types:
      - released # Aktivira workflow samo na događaj "released".

permissions: {} # Workflow nema početne dozvole.

jobs:
  update:
    name: Update Changelog File # Naziv posla.
    permissions:
      contents: write # Omogućava zapisivanje sadržaja u repozitorijum.

    uses: laravel/.github/.github/workflows/update-changelog.yml@main
    # Ponovno koristi workflow iz Laravel-ovog udaljenog repozitorijuma.